on: push

jobs:
  build-for-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2
      - run: ./mvnw install
      - uses: actions/upload-artifact@v3
        with:
          name: debian-${{ github.run_id }}
          path: desktop/target/*.deb
  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2
      - run: ./mvnw install
      - uses: actions/upload-artifact@v3
        with:
          name: windows-${{ github.run_id }}
          path: desktop/target/*.exe
  build-for-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v2
      - run: ./mvnw install
      - uses: actions/upload-artifact@v3
        with:
          name: macos-${{ github.run_id }}
          path: desktop/target/*.dmg
